site_name: Owen Stillman's Smart Home
site_author: Owen Stillman
site_description: My Smart Home Setup

repo_url: https://github.com/OStillman/HomeAssistant-Public
repo_name: OStillman/HomeAssistant-Public

theme:
  name: material
  custom_dir: docs/overrides
  pallete:
    scheme: preference
    primary: amber
    accent: orange
  features:
    - navgiation.tabs
    - navigation.tabs.sticky
    - navigation.sections


nav:
  - Home: index.md
  - Hardware: hardware.md
  - Home Assistant: home_assistant.md
  - Self-Development: 
    - Introduction: development/development.md
    - ODACShows: development/odacshows.md


markdown_extensions:
  - attr_list
