site_name: Owen Stillman's Home Server
site_author: Owen Stillman
site_description: My Home Server Usuage, Setup and General Config

theme:
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: orange
  features:
    - navgiation.tabs
    - navigation.sections


nav:
  - 'Home': index.md
  - 'Architecture':
    - 'Zero Trust' : 'architecture/zero-trust.md'
  - 'Applications':
    - 'Home Assistant': 'applications/home-assistant.md'
    - 'Zigbee2MQTT': 'applications/zigbee2mqtt.md'
    - 'Mealie': 'applications/mealie.md'


markdown_extensions:
  - attr_list
  - admonition
