site_name: Owen Stillman's Smart Home
site_author: Owen Stillman
site_description: My Smart Home Setup

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: preference
    primary: amber
    accent: orange
  features:
    - navgiation.tabs
    - navigation.sections


nav:
  - Home: index.md


markdown_extensions:
  - attr_list
  - admonition
